house/signin/urls.py
from django.conf.urls import patterns, url, include

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.start,
        name='start'),
    url(r'^failed/$', views.failed,
        name='failed'),
    url(r'^register/$', views.register,
        name='register'),
    url(r'^register/done/$', views.done,
        name='done'),
    url(r'^account/$', views.account,
        name='account'),
    url(r'^signout/$', views.signout,
        name='signout'),
    url(r'^signedout/$', views.signedout,
        name='signedout'),
)

house/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

import jingo.monkey
jingo.monkey.patch()

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^browserid/', include('django_browserid.urls')),
    url(r'^signin/', include('house.signin.urls', namespace='signin')),
    url(r'', include('house.main.urls', namespace='main')),
)


## In DEBUG mode, serve media files through Django.
if settings.DEBUG:
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns(
        '',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    )
    urlpatterns += staticfiles_urlpatterns()

house/main/models.py
import stat
import uuid
import os
import hashlib
import datetime
import unicodedata

from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.utils.timezone import utc

from sorl.thumbnail import ImageField


def now():
    return datetime.datetime.utcnow().replace(tzinfo=utc)


def identifier_maker(length):
    def maker():
        return uuid.uuid4().hex[:length]
    return maker


class Address(models.Model):
    line1 = models.CharField(max_length=100)
    line2 = models.CharField(max_length=100, null=True, blank=True)
    zip_code = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, default='United States')
    timezone = models.CharField(max_length=100, null=True, blank=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)

    added = models.DateTimeField(default=now)
    modified = models.DateTimeField(default=now)


class House(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, db_index=True)
    owners = models.ManyToManyField(User, related_name='houses')
    address = models.ForeignKey(Address, null=True)

    added = models.DateTimeField(default=now)
    modified = models.DateTimeField(default=now)

    def __repr__(self):
        return "<%s: %r>" % (self.__class__.__name__, self.address.line1)

    @classmethod
    def get_house(self, user):
        return self.objects.get(owners=user)


def _upload_path(tag):
    def _upload_path_tagged(instance, filename):
        if isinstance(filename, unicode):
            filename = (
                unicodedata
                .normalize('NFD', filename)
                .encode('ascii', 'ignore')
            )
        _now = now()
        path = os.path.join(
#            "%05d" % instance.pk,
            _now.strftime('%Y'),
            _now.strftime('%m'),
            _now.strftime('%d')
        )
        hashed_filename = (hashlib.md5(filename +
                           str(now().microsecond)).hexdigest())
        __, extension = os.path.splitext(filename)
        return os.path.join(tag, path, hashed_filename + extension)
    return _upload_path_tagged


class Photo(models.Model):
    house = models.ForeignKey(House)
    photo = ImageField(upload_to=_upload_path('photos'))
    cover = models.DateTimeField(blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    added_by = models.ForeignKey(User)
    added = models.DateTimeField(default=now)
    modified = models.DateTimeField(default=now)

    def set_cover_photo(self):
        self.cover = now()

    @classmethod
    def get_cover_photo(self, house):
        _qs = self.objects.filter(house=house).exclude(cover=None)
        for p in _qs.order_by('-cover')[:1]:
            return p


class Document(models.Model):
    house = models.ForeignKey(House)
    file = models.FileField(upload_to=_upload_path('documents'))
    filename = models.CharField(max_length=100)
    #picture = ImageField(upload_to=_upload_path('documents'), blank=True, null=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    document_type = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    searchable_text = models.TextField(blank=True, null=True)
    text_extracted = models.BooleanField(default=False)
    added_by = models.ForeignKey(User)

    added = models.DateTimeField(default=now)
    modified = models.DateTimeField(default=now)

    def __repr__(self):
        return '<%s: %s>' % (self.__class__.__name__, self.file.path)

    @property
    def file_size(self):
        return os.stat(self.file.path)[stat.ST_SIZE]


class Invitation(models.Model):
    house = models.ForeignKey(House)
    user = models.ForeignKey(User)
    email_address = models.EmailField()
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    send_date = models.DateTimeField(blank=True, null=True)
    identifier = models.CharField(max_length=32, default=identifier_maker(16))

    added = models.DateTimeField(default=now)
    modified = models.DateTimeField(default=now)


@receiver(models.signals.pre_save, sender=House)
@receiver(models.signals.pre_save, sender=Photo)
@receiver(models.signals.pre_save, sender=Document)
@receiver(models.signals.pre_save, sender=Address)
@receiver(models.signals.pre_save, sender=Invitation)
def update_modified(sender, instance, raw, *args, **kwargs):
    if raw:
        return
    instance.modified = now()

house/base/forms.py
from django import forms


class _BaseForm(object):
    def clean(self):
        cleaned_data = super(_BaseForm, self).clean()
        for field in cleaned_data:
            if isinstance(cleaned_data[field], basestring):
                cleaned_data[field] = (
                    cleaned_data[field].replace('\r\n', '\n')
                    .replace(u'\u2018', "'").replace(u'\u2019', "'").strip())

        return cleaned_data


class BaseModelForm(_BaseForm, forms.ModelForm):
    pass


class BaseForm(_BaseForm, forms.Form):
    pass

house/signin/forms.py
from house.base.forms import BaseForm, BaseModelForm
from house.main import models


class HouseForm(BaseModelForm):

    class Meta:
        model = models.House
        fields = ('name',)


class AddressForm(BaseModelForm):

    class Meta:
        model = forms.Address
        fields = ('line1', 'line2', 'state', 'zip_code', 'country',)

house/signin/views.py
from django import http
from django.core.urlresolvers import reverse
from django.utils.timezone import utc
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db import transaction
from django.template.defaultfilters import slugify

from house.main import forms
from house.main import models


def start(request):
    context = {'house': None}
    if request.user.is_authenticated():
        try:
            context['house'] = models.House.get_house(request.user)
        except models.House.DoesNotExist:
            pass
    return render(request, 'signin/start.html', context)


def failed(request):
    context = {}
    if request.user.is_authenticated():
        return redirect('signin:start')

    return render(request, 'signin/failed.html', context)


@login_required
@transaction.commit_on_success
def register(request):
    context = {'existing': None}
    if request.method == 'POST':
        form = forms.AddressForm(request.POST)
        if form.is_valid():
            # is there a house with the exact same address and town?
            existing = models.House.objects.filter(
                address__line1__iexact=form.cleaned_data['line1'],
                address__city__iexact=form.cleaned_data['city']
            )
            if existing:
                context['existing'] = existing
            else:
                address = form.save()
                house = models.House.objects.create(
                    name=address.line1,
                    slug=slugify(address.line1),
                    address=address,
                )
                house.owners.add(request.user)
                url = reverse('signin:done')
                return redirect(url)
    else:
        initial = {'country': 'United States'}
        form = forms.AddressForm(initial=initial)
    context['form'] = form
    form.fields['line1'].label = 'Adress line 1'
    form.fields['line2'].label = 'Adress line 2 (optional)'
    for field in form.fields:
        form.fields[field].widget.attrs['class'] = 'pure-input-1-3'
    return render(request, 'signin/register.html', context)


@login_required
def done(request):
    context = {}
    context['house'] = models.House.get_house(request.user)
    return render(request, 'signin/done.html', context)


@login_required
def account(request):
    context = {}
    return render(request, 'signin/account.html', context)


@login_required
def signout(request):
    context = {}
    return render(request, 'signin/signout.html', context)


def signedout(request):
    return render(request, 'signin/signedout.html')

house/signin/templates/signin/account.html
{% extends "signin/base.html" %}


{% block content_inner %}

    <div class="splash">
        <div class="pure-g-r">

            <div class="pure-u-2-3">
                <div class="l-box splash-text">
                    <h3>Your Account</h3>

                    <h1 class="splash-head">
                        Your Account
                    </h1>

                    <h2 class="splash-subhead">
                        Stuff
                    </h2>

                </div>
            </div>
        </div>
    </div>



{% endblock %}

house/signin/templates/signin/base.html
{% extends "base.html" %}

house/signin/templates/signin/done.html
{% extends "signin/base.html" %}


{% block content_inner %}

    <div class="splash">
        <div class="pure-g-r">

            <div class="pure-u-2-3">
                <div class="l-box splash-text">
                     <h3></h3>

                    <h1 class="splash-head">
                        Excellent!
                    </h1>

                    <h2 class="splash-subhead">
                        You're on your way to become an even prouder house owner!
                    </h2>

                    <p>
                        <a class="pure-button primary-button"
                           href="{{ url('main:home', house.slug) }}">Proceed to your own home page for <b>{{ house.name }}</b></a>
                    </p>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

house/signin/templates/signin/failed.html
{% extends "signin/start.html" %}


{% block content_inner %}
{{ browserid_info() }}

        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Sign In Failed</h4>

                    <p>
                        For some reason the authentication with <b>Persona</b> failed. <br>
                        Perhaps it was just a temporary thing or something went wrong
                        with the password you entered. <br>
                        Please try again.
                    </p>
                </div>
            </div>

            <div class="pure-u-1-3">
                <div class="l-box">
                    <a  style="margin:100px;" href="#" data-next="/signin/" class="browserid-login persona-button dark"><span>Sign in with your Email</span></a>
                </div>
            </div>
        </div>


{% endblock %}

house/signin/templates/signin/register.html
{% extends "signin/base.html" %}

{% block extra_head %}
{% endblock %}

{% block content_inner %}

        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1">
                <div class="l-box">
                    <h4 class="content-subhead">Register</h4>

                    {% if existing %}
                    <div class="existing">
                    <h3>Hmm... A house with that address has already been registered.</h3>
                    {% for house in existing %}
                    <p><b>{{ house.name }}</b> is currently owned by:</p>
                    <ul>
                      {% for user in house.owners.all() %}
                      <li>{{ user.email | obfuscate_email }}</li>
                      {% endfor %}
                    </ul>
                    {% endfor %}
                    <p>Perhaps you have multiple accounts but logged in with the wrong email address?</p>
                    </div>
                    {% endif %}

                    <h3>Minimal Information to Register</h3>

                    <form class="search-form pure-form">
                      <fieldset>
                      <label for="id_address">Address:</label>
                      <input type="text" name="address" id="id_address"
                        class="pure-input-1-2 pure-input-rounded"
                        placeholder="for example: 1234 Fake street, CA">
                      <button type="submit" class="pure-button xpure-button-primary">Search</button>
                      </fieldset>
                    </form>

                    <form method="post" class="register pure-form pure-form-stacked" style="display:none">
                      {{ csrf() }}
                      <fieldset>
                        {{ pureform(form) }}
                        <button type="submit" class="pure-button pure-button-primary">Proceed </button>
                      </fieldset>
                    </form>
                </div><!-- /l-box -->
            </div><!-- /pure-u-1 -->
        </div>


        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1">
                <div class="l-box">
                  <div class="loading" style="display:none">
                  Searching...
                  </div>
                  <div class="alternatives" style="display:none">
                  <h4>Is it...?</h4>
                  <ul>

                  </ul>
                  <a href="#" class="wasnot">No? Enter more of the address</a>
                  </div>
                </div>
            </div>
        </div>



{% endblock %}

{% block extra_javascript %}
{{ super() }}
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script src="{{ static('signin/js/register.js') }}"></script>
{% endblock %}

house/signin/templates/signin/signedout.html
{% extends "signin/base.html" %}


{% block content_inner %}

    <div class="splash">
        <div class="pure-g-r">

            <div class="pure-u-1">
                <div class="l-box splash-text">

                    <h3>You have signed out</h3>

                    <p style="text-align: center">
                    <a href="/" class="pure-button primary-button">Go the the Home page</a>
                    <a href="{{ url('signin:start') }}" class="pure-button primary-button">Sign in again</a>
                    </p>

                </div>
            </div>
        </div>
    </div>



{% endblock %}

house/signin/templates/signin/signout.html
{% extends "signin/base.html" %}


{% block content_inner %}
{{ browserid_info() }}

    <div class="splash">
        <div class="pure-g-r">

            <div class="pure-u-1">
                <div class="l-box splash-text">

                <p style="text-align: center">
                    <a href="/browserid/logout/" class="pure-button primary-button browserid-logout">Sign out</a>
                </p>

                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block extra_javascript %}
{{ super() }}
{{ browserid_js() }}
{% endblock %}

house/signin/templates/signin/start.html
{% extends "signin/base.html" %}

{% block extra_head %}
<link rel="stylesheet" href="{{ static('signin/css/persona-buttons.css') }}">
{% endblock %}

{% block content_inner %}
{{ browserid_info() }}

        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Sign in first</h4>

                    <h3>Let Mozilla's Persona handle the password stuff</h3>
                    <p>
                        Because <b>{{ page_title }}</b> doesn't want to store your password,
                        we outsource that entirely to <b>Mozilla Persona</b>. That way you can
                        securely sign in with your existing email address is a secure way.
                    </p>
                </div>
            </div>

            <div class="pure-u-1-3">
                <div class="l-box">
                    {% if user.is_authenticated() %}
                    <p>You're already signed in.</p>
                      {% if house %}
                      <p><a href="{{ url('main:home', house.slug) }}">Go to <b>{{ house.name }}</b></p>
                      {% else %}
                      <p><a href="{{ url('signin:register') }}">Proceed to registration</a></p>
                      {% endif %}

                    {% else %}
                    <a href="#" data-next="/signin/" class="browserid-login persona-button dark"><span>Sign in with your Email</span></a>
                    {# {{ browserid_login(text='Login') }} #}
                    {% endif %}
                </div>
            </div>
        </div>



{% endblock %}

{% block extra_javascript %}
{{ super() }}
{{ browserid_js() }}
{% endblock %}